version: '2'
services:
    otodepom-app:
        image: otodepom
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://otodepom-postgresql:5432/otodepom
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    otodepom-postgresql:
        extends:
            file: postgresql.yml
            service: otodepom-postgresql
