version: '2'
services:
    otodepom-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/otodepom/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=otodepom
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
